In [1]:
import numpy as np

array = np.random.rand(2, 2, 2, 2)
print(array)

[[[[0.48782094 0.20034994]
   [0.47169756 0.60167405]]

  [[0.25559492 0.14674866]
   [0.866697   0.21758722]]]


 [[[0.12509768 0.05436592]
   [0.86504729 0.63285464]]

  [[0.7073689  0.04172665]
   [0.90444197 0.67365676]]]]


In [ ]:
# importing numpy


print(array[..., 0])
#print(array[0])


In [2]:
from Wavenet import WaveNet
import torch

x = torch.rand(2, 1, 1000)
wavenet = WaveNet(1, 1, 2, 3, 4)
wavenet.calculateOutputSize(x)

955

In [3]:
from Wavenet import CasualDilatedConv1D
import torch

x = torch.rand(2, 1, 1000)
Conv1D = CasualDilatedConv1D(1, 1, 2, dilation=1)
output = Conv1D(x)
print(output.size())

TypeError: conv1d(): argument 'padding' (position 5) must be tuple of ints, not str